exp: 
    name: 'baseline'
    checkpoint_dir: 'checkpoints'
    num_workers: 8
    batch_size: 32
    num_epochs: 100000

model:
    encoder: 'dgcnn'
    pc_feat_dim: 512
    transformer_feat_dim: 1024
    num_heads: 4
    num_blocks: 1

data:
    root_dir: ''
    train_csv_file: ''
    test_csv_file: ''
    num_pc_points: 1024

optimizer:
    lr: 1e-3
    lr_decay: 0.0
    weight_decay: 1e-6
    lr_clip: 1e-5
